DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS outputs;

CREATE TABLE devices (
       id INTEGER PRIMARY KEY AUTOINCREMENT,
       title TEXT NOT NULL,
       channel INTEGER
);

CREATE TABLE outputs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    channel INTEGER NOT NULL,
    activation INTEGER NOT NULL
);